import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navigation Pane */}
        <nav className="bg-gray-800 text-white p-4 shadow-md">
          <div className="max-w-4xl mx-auto">
            <Link
              href="/"
              className="text-lg font-semibold hover:text-blue-300 transition-colors"
            >
              Quiz App
            </Link>
          </div>
        </nav>
        
        {/* Main Content */}
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
